apiVersion: v1
kind: Pod
metadata: 
  name: nodeapp
  labels: 
    app: nodeapp
spec:
  containers:
  - image: stepanow/nodeapp:1.0.0
    name: nodeapp
    ports: 
    - containerPort: 8080
      protocol: TCP
