apiVersion: v1
data:
  policy.csv: |
    g, user1, role:admin
    g, image-updater, role:image-updater
    p, role:image-updater, applications, get, */*, allow
    p, role:image-updater, applications, update, */*, allow
  policy.default: role.readonly
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"policy.csv":"g, user1, role:admin\n","policy.default":"role:''"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2023-09-07T05:18:29Z","labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"615394","uid":"7be78372-c56a-42d2-9b1d-eea43fdcda1d"}}
  creationTimestamp: "2023-09-07T05:18:29Z"
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd
  resourceVersion: "619545"
  uid: 7be78372-c56a-42d2-9b1d-eea43fdcda1d
